-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2020-01-22 00:42:31 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



DROP VIEW Cene_obroka CASCADE CONSTRAINTS 
;

DROP VIEW Kupovina_hrane CASCADE CONSTRAINTS 
;

DROP VIEW Menza CASCADE CONSTRAINTS 
;

DROP VIEW Osnovni_podaci CASCADE CONSTRAINTS 
;

DROP VIEW Prodaja_obroka CASCADE CONSTRAINTS 
;

DROP VIEW Radnici_u_menzi CASCADE CONSTRAINTS 
;

DROP VIEW Radnici_u_SZUO CASCADE CONSTRAINTS 
;

DROP TABLE cenovnik CASCADE CONSTRAINTS;

DROP TABLE dnevno_posluzenje_hrane CASCADE CONSTRAINTS;

DROP TABLE drzava CASCADE CONSTRAINTS;

DROP TABLE fakultet CASCADE CONSTRAINTS;

DROP TABLE grad CASCADE CONSTRAINTS;

DROP TABLE kasa CASCADE CONSTRAINTS;

DROP TABLE obrok CASCADE CONSTRAINTS;

DROP TABLE racun CASCADE CONSTRAINTS;

DROP TABLE radnik CASCADE CONSTRAINTS;

DROP TABLE radnik_u_menzi CASCADE CONSTRAINTS;

DROP TABLE radnik_u_szuo CASCADE CONSTRAINTS;

DROP TABLE restoran CASCADE CONSTRAINTS;

DROP TABLE salter CASCADE CONSTRAINTS;

DROP TABLE sluzba_ishrane CASCADE CONSTRAINTS;

DROP TABLE smer CASCADE CONSTRAINTS;

DROP TABLE stanje_na_kartici CASCADE CONSTRAINTS;

DROP TABLE status_studenta CASCADE CONSTRAINTS;

DROP TABLE stavka CASCADE CONSTRAINTS;

DROP TABLE studentska_kartica CASCADE CONSTRAINTS;

DROP TABLE univerzitet CASCADE CONSTRAINTS;

CREATE TABLE cenovnik (
    dat_pv             DATE NOT NULL,
    dat_zv             DATE,
    cena_ob            NUMBER NOT NULL,
    ob_sifra_ob        INTEGER NOT NULL,
    status_stud_id_st  INTEGER NOT NULL
);

ALTER TABLE cenovnik ADD CONSTRAINT cenovnik_pk PRIMARY KEY ( dat_pv,
                                                              ob_sifra_ob );

CREATE TABLE dnevno_posluzenje_hrane (
    id_ph                  INTEGER NOT NULL,
    kol_ph                 INTEGER NOT NULL,
    dat_ph                 DATE NOT NULL,
    sal_id_sal             INTEGER NOT NULL,
    sal_id_res             INTEGER NOT NULL,
    ob_sifra_ob            INTEGER NOT NULL,
    rad_u_menzi_sifra_rad  INTEGER NOT NULL
);

ALTER TABLE dnevno_posluzenje_hrane
    ADD CONSTRAINT dnevno_posluzenje_hrane_pk PRIMARY KEY ( id_ph,
                                                            sal_id_sal,
                                                            sal_id_res );

CREATE TABLE drzava (
    id_drzave   INTEGER NOT NULL,
    naz_drzave  VARCHAR2(1000) NOT NULL
);

ALTER TABLE drzava ADD CONSTRAINT drzava_pk PRIMARY KEY ( id_drzave );

CREATE TABLE fakultet (
    id_fak      INTEGER NOT NULL,
    naz_fak     VARCHAR2(30 CHAR) NOT NULL,
    uni_id_uni  INTEGER NOT NULL
);

ALTER TABLE fakultet ADD CONSTRAINT fakultet_pk PRIMARY KEY ( id_fak,
                                                              uni_id_uni );

CREATE TABLE grad (
    id_grada          INTEGER NOT NULL,
    naz_grada         VARCHAR2(30 CHAR) NOT NULL,
    drzava_id_drzave  INTEGER NOT NULL
);

ALTER TABLE grad ADD CONSTRAINT grad_pk PRIMARY KEY ( id_grada,
                                                      drzava_id_drzave );

CREATE TABLE kasa (
    id_kase INTEGER NOT NULL
);

ALTER TABLE kasa ADD CONSTRAINT kasa_pk PRIMARY KEY ( id_kase );

CREATE TABLE obrok (
    sifra_ob  INTEGER NOT NULL,
    naz_ob    VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE obrok ADD CONSTRAINT obrok_pk PRIMARY KEY ( sifra_ob );

CREATE TABLE racun (
    id_rac                   INTEGER NOT NULL,
    uk_cena                  NUMBER NOT NULL,
    dat_izd_rac              DATE NOT NULL,
    radnik_u_szuo_sifra_rad  INTEGER NOT NULL,
    kasa_id_kase             INTEGER NOT NULL,
    stud_kartica_br_kar      INTEGER NOT NULL
);

ALTER TABLE racun ADD CONSTRAINT racun_pk PRIMARY KEY ( id_rac,
                                                        kasa_id_kase );

CREATE TABLE radnik (
    sifra_rad     INTEGER NOT NULL,
    jmbg_rad      INTEGER NOT NULL,
    dat_rodj_rad  DATE NOT NULL,
    ime_rad       VARCHAR2(30 CHAR) NOT NULL,
    prez_rad      VARCHAR2(30 CHAR) NOT NULL,
    si_id_si      INTEGER NOT NULL
);

ALTER TABLE radnik ADD CONSTRAINT radnik_pk PRIMARY KEY ( sifra_rad );

ALTER TABLE radnik ADD CONSTRAINT radnik_jmbg_rad_un UNIQUE ( jmbg_rad );

CREATE TABLE radnik_u_menzi (
    sifra_rad INTEGER NOT NULL
);

ALTER TABLE radnik_u_menzi ADD CONSTRAINT radnik_u_menzi_pk PRIMARY KEY ( sifra_rad );

CREATE TABLE radnik_u_szuo (
    sifra_rad INTEGER
        CONSTRAINT "NNC_Radnik u SZUO_sifra_rad" NOT NULL
);

ALTER TABLE radnik_u_szuo ADD CONSTRAINT radnik_u_szuo_pk PRIMARY KEY ( sifra_rad );

CREATE TABLE restoran (
    id_res   INTEGER NOT NULL,
    naz_res  VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE restoran ADD CONSTRAINT restoran_pk PRIMARY KEY ( id_res );

CREATE TABLE salter (
    id_sal      INTEGER NOT NULL,
    res_id_res  INTEGER NOT NULL
);

ALTER TABLE salter ADD CONSTRAINT salter_pk PRIMARY KEY ( id_sal,
                                                          res_id_res );

CREATE TABLE sluzba_ishrane (
    id_si      INTEGER NOT NULL,
    rad_vreme  VARCHAR2(4000)
);

ALTER TABLE sluzba_ishrane ADD CONSTRAINT sluzba_ishrane_pk PRIMARY KEY ( id_si );

CREATE TABLE smer (
    sifra_smera     INTEGER NOT NULL,
    naz_smera       VARCHAR2(1000) NOT NULL,
    fak_id_fak      INTEGER NOT NULL,
    fak_uni_id_uni  INTEGER NOT NULL
);

ALTER TABLE smer
    ADD CONSTRAINT smer_pk PRIMARY KEY ( sifra_smera,
                                         fak_id_fak,
                                         fak_uni_id_uni );

CREATE TABLE stanje_na_kartici (
    stud_kartica_br_kar  INTEGER NOT NULL,
    ob_sifra_ob          INTEGER NOT NULL,
    kol_kar              INTEGER
);

ALTER TABLE stanje_na_kartici ADD CONSTRAINT stanje_na_kartici_pk PRIMARY KEY ( stud_kartica_br_kar,
                                                                                ob_sifra_ob );

CREATE TABLE status_studenta (
    id_st    INTEGER NOT NULL,
    opis_st  VARCHAR2(4000),
    naz_st   VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE status_studenta ADD CONSTRAINT status_studenta_pk PRIMARY KEY ( id_st );

CREATE TABLE stavka (
    rbr_sta          INTEGER NOT NULL,
    kol_sta          INTEGER NOT NULL,
    iznos            NUMBER NOT NULL,
    rac_id_rac       INTEGER NOT NULL,
    rac_id_kase      INTEGER NOT NULL,
    cen_dat_pv       DATE NOT NULL,
    cen_ob_sifra_ob  INTEGER NOT NULL
);

ALTER TABLE stavka
    ADD CONSTRAINT stavka_pk PRIMARY KEY ( rbr_sta,
                                           rac_id_rac,
                                           rac_id_kase );

CREATE TABLE studentska_kartica (
    br_kar               INTEGER NOT NULL,
    isic_br              VARCHAR2(30 CHAR) NOT NULL,
    jmbg_stud            INTEGER NOT NULL,
    br_ind               VARCHAR2(30 CHAR) NOT NULL,
    god_upisa            INTEGER NOT NULL,
    prez_stud            VARCHAR2(30 CHAR) NOT NULL,
    dat_rodj_stud        DATE NOT NULL,
    dat_vaz_kar          DATE NOT NULL,
    ime_stud             VARCHAR2(30 CHAR) NOT NULL,
    dat_vadj_kar         DATE NOT NULL,
    status_stud_id_st    INTEGER NOT NULL,
    id_grada_mr          INTEGER NOT NULL,
    id_drzave_mr         INTEGER NOT NULL,
    id_grada_ms          INTEGER NOT NULL,
    id_drzave_ms         INTEGER NOT NULL,
    smer_sifra_smera     INTEGER NOT NULL,
    smer_fak_id_fak      INTEGER NOT NULL,
    smer_fak_uni_id_uni  INTEGER NOT NULL,
    dat_vaz_st           DATE,
    ulica                VARCHAR2(30 CHAR),
    br_ulice             INTEGER
);

ALTER TABLE studentska_kartica ADD CONSTRAINT studentska_kartica_pk PRIMARY KEY ( br_kar );

ALTER TABLE studentska_kartica ADD CONSTRAINT stud_kartica_isic_br_un UNIQUE ( isic_br );

ALTER TABLE studentska_kartica ADD CONSTRAINT stud_kartica_jmbg_un UNIQUE ( jmbg_stud );

CREATE TABLE univerzitet (
    id_uni   INTEGER NOT NULL,
    naz_uni  VARCHAR2(30 CHAR) NOT NULL
);

ALTER TABLE univerzitet ADD CONSTRAINT univerzitet_pk PRIMARY KEY ( id_uni );

ALTER TABLE cenovnik
    ADD CONSTRAINT cenovnik_obrok_fk FOREIGN KEY ( ob_sifra_ob )
        REFERENCES obrok ( sifra_ob );

ALTER TABLE cenovnik
    ADD CONSTRAINT cenovnik_status_studenta_fk FOREIGN KEY ( status_stud_id_st )
        REFERENCES status_studenta ( id_st );

ALTER TABLE dnevno_posluzenje_hrane
    ADD CONSTRAINT dnevno_ph_obrok_fk FOREIGN KEY ( ob_sifra_ob )
        REFERENCES obrok ( sifra_ob );

ALTER TABLE dnevno_posluzenje_hrane
    ADD CONSTRAINT dnevno_ph_rad_u_menzi_fk FOREIGN KEY ( rad_u_menzi_sifra_rad )
        REFERENCES radnik_u_menzi ( sifra_rad );

ALTER TABLE dnevno_posluzenje_hrane
    ADD CONSTRAINT dnevno_ph_salter_fk FOREIGN KEY ( sal_id_sal,
                                                     sal_id_res )
        REFERENCES salter ( id_sal,
                            res_id_res );

ALTER TABLE fakultet
    ADD CONSTRAINT fakultet_univerzitet_fk FOREIGN KEY ( uni_id_uni )
        REFERENCES univerzitet ( id_uni );

ALTER TABLE grad
    ADD CONSTRAINT grad_drzava_fk FOREIGN KEY ( drzava_id_drzave )
        REFERENCES drzava ( id_drzave );

ALTER TABLE racun
    ADD CONSTRAINT racun_kasa_fk FOREIGN KEY ( kasa_id_kase )
        REFERENCES kasa ( id_kase );

ALTER TABLE racun
    ADD CONSTRAINT racun_radnik_u_szuo_fk FOREIGN KEY ( radnik_u_szuo_sifra_rad )
        REFERENCES radnik_u_szuo ( sifra_rad );

ALTER TABLE racun
    ADD CONSTRAINT racun_studentska_kartica_fk FOREIGN KEY ( stud_kartica_br_kar )
        REFERENCES studentska_kartica ( br_kar );

ALTER TABLE radnik
    ADD CONSTRAINT radnik_sluzba_ishrane_fk FOREIGN KEY ( si_id_si )
        REFERENCES sluzba_ishrane ( id_si );

ALTER TABLE radnik_u_menzi
    ADD CONSTRAINT radnik_u_menzi_radnik_fk FOREIGN KEY ( sifra_rad )
        REFERENCES radnik ( sifra_rad );

ALTER TABLE radnik_u_szuo
    ADD CONSTRAINT "Radnik u SZUO_Radnik_FK" FOREIGN KEY ( sifra_rad )
        REFERENCES radnik ( sifra_rad );

ALTER TABLE salter
    ADD CONSTRAINT salter_restoran_fk FOREIGN KEY ( res_id_res )
        REFERENCES restoran ( id_res );

ALTER TABLE smer
    ADD CONSTRAINT smer_fakultet_fk FOREIGN KEY ( fak_id_fak,
                                                  fak_uni_id_uni )
        REFERENCES fakultet ( id_fak,
                              uni_id_uni );

ALTER TABLE stanje_na_kartici
    ADD CONSTRAINT stanje_na_kartici_obrok_fk FOREIGN KEY ( ob_sifra_ob )
        REFERENCES obrok ( sifra_ob );

ALTER TABLE stanje_na_kartici
    ADD CONSTRAINT stanje_stud_kartica_fk FOREIGN KEY ( stud_kartica_br_kar )
        REFERENCES studentska_kartica ( br_kar );

ALTER TABLE stavka
    ADD CONSTRAINT stavka_cenovnik_fk FOREIGN KEY ( cen_dat_pv,
                                                    cen_ob_sifra_ob )
        REFERENCES cenovnik ( dat_pv,
                              ob_sifra_ob );

ALTER TABLE stavka
    ADD CONSTRAINT stavka_racun_fk FOREIGN KEY ( rac_id_rac,
                                                 rac_id_kase )
        REFERENCES racun ( id_rac,
                           kasa_id_kase );

ALTER TABLE studentska_kartica
    ADD CONSTRAINT stud_kartica_grad_fk FOREIGN KEY ( id_grada_mr,
                                                      id_drzave_mr )
        REFERENCES grad ( id_grada,
                          drzava_id_drzave );

ALTER TABLE studentska_kartica
    ADD CONSTRAINT stud_kartica_grad_fkv2 FOREIGN KEY ( id_grada_ms,
                                                        id_drzave_ms )
        REFERENCES grad ( id_grada,
                          drzava_id_drzave );

ALTER TABLE studentska_kartica
    ADD CONSTRAINT stud_kartica_smer_fk FOREIGN KEY ( smer_sifra_smera,
                                                      smer_fak_id_fak,
                                                      smer_fak_uni_id_uni )
        REFERENCES smer ( sifra_smera,
                          fak_id_fak,
                          fak_uni_id_uni );

ALTER TABLE studentska_kartica
    ADD CONSTRAINT stud_kartica_stat_stud_fk FOREIGN KEY ( status_stud_id_st )
        REFERENCES status_studenta ( id_st );

CREATE OR REPLACE VIEW Cene_obroka ( naz_st, opis_st, naz_ob, cena_ob, dat_zv, dat_pv ) AS
SELECT
    status_studenta.naz_st,
    status_studenta.opis_st,
    obrok.naz_ob,
    cenovnik.cena_ob,
    cenovnik.dat_zv,
    cenovnik.dat_pv
FROM
         cenovnik
    INNER JOIN obrok ON obrok.sifra_ob = cenovnik.ob_sifra_ob
    INNER JOIN status_studenta ON status_studenta.id_st = cenovnik.status_stud_id_st 
;

CREATE OR REPLACE VIEW Kupovina_hrane ( dat_izd_rac, isic_br, prez_stud, ime_stud, naz_st, iznos, kol_sta, stud_kartica_br_kar, naz_ob, kol_kar ) AS
SELECT
    racun.dat_izd_rac,
    studentska_kartica.isic_br,
    studentska_kartica.prez_stud,
    studentska_kartica.ime_stud,
    status_studenta.naz_st,
    stavka.iznos,
    stavka.kol_sta,
    racun.stud_kartica_br_kar,
    obrok.naz_ob,
    stanje_na_kartici.kol_kar
FROM
         studentska_kartica
    INNER JOIN racun ON studentska_kartica.br_kar = racun.stud_kartica_br_kar
    INNER JOIN status_studenta ON status_studenta.id_st = studentska_kartica.status_stud_id_st
    INNER JOIN stavka ON racun.id_rac = stavka.rac_id_rac
    INNER JOIN cenovnik ON cenovnik.dat_pv = stavka.cen_dat_pv
    INNER JOIN obrok ON obrok.sifra_ob = cenovnik.ob_sifra_ob
    INNER JOIN stanje_na_kartici ON obrok.sifra_ob = stanje_na_kartici.ob_sifra_ob AND stanje_na_kartici.stud_kartica_br_kar = studentska_kartica.br_kar 
;

CREATE OR REPLACE VIEW Menza ( kol_ph, dat_ph, naz_ob, prez_rad, ime_rad, sifra_rad ) AS
SELECT
    dnevno_posluzenje_hrane.kol_ph,
    dnevno_posluzenje_hrane.dat_ph,
    obrok.naz_ob,
    --salter.id_sal,
    --restoran.naz_res,
    radnik.prez_rad,
    radnik.ime_rad,
    radnik.sifra_rad
FROM
    dnevno_posluzenje_hrane
    INNER JOIN radnik ON radnik.sifra_rad = dnevno_posluzenje_hrane.rad_u_menzi_sifra_rad
    INNER JOIN obrok ON obrok.sifra_ob = dnevno_posluzenje_hrane.ob_sifra_ob
    --INNER JOIN salter ON salter.id_sal = dnevno_posluzenje_hrane.sal_id_sal
    --INNER JOIN restoran ON restoran.id_res = salter.res_id_res
;

CREATE OR REPLACE VIEW Kolicina_po_rad ( sifra_rad, prez_rad, ime_rad, kolicina_dor) AS
SELECT 
    radnik_u_menzi.sifra_rad,radnik.prez_rad,radnik.ime_rad,sum(dnevno_posluzenje_hrane.kol_ph)
FROM 
    dnevno_posluzenje_hrane
    INNER JOIN obrok ON obrok.sifra_ob = dnevno_posluzenje_hrane.ob_sifra_ob
    INNER JOIN radnik_u_menzi ON radnik_u_menzi.sifra_rad = dnevno_posluzenje_hrane.rad_u_menzi_sifra_rad
    INNER JOIN radnik ON radnik.sifra_rad = radnik_u_menzi.sifra_rad
group by radnik_u_menzi.sifra_rad,radnik.prez_rad,radnik.ime_rad
;

CREATE OR REPLACE VIEW Osnovni_podaci ( opis_st, naz_st, naz_smera, kol_kar, naz_ob, br_kar, isic_br, jmbg_stud, br_ind, god_upisa, prez_stud, dat_rodj_stud, dat_vaz_kar, ime_stud, dat_vadj_kar, dat_vaz_st, ulica, br_ulice, naz_fak, grad_mr, drzava_mr, grad_ms, drzava_ms ) AS
SELECT
    status_studenta.opis_st,
    status_studenta.naz_st,
    smer.naz_smera,
    stanje_na_kartici.kol_kar,
    obrok.naz_ob,
    studentska_kartica.br_kar,
    studentska_kartica.isic_br,
    studentska_kartica.jmbg_stud,
    studentska_kartica.br_ind,
    studentska_kartica.god_upisa,
    studentska_kartica.prez_stud,
    studentska_kartica.dat_rodj_stud,
    studentska_kartica.dat_vaz_kar,
    studentska_kartica.ime_stud,
    studentska_kartica.dat_vadj_kar,
    studentska_kartica.dat_vaz_st,
    studentska_kartica.ulica,
    studentska_kartica.br_ulice,
    fakultet.naz_fak,
    grad_mr.naz_grada       AS "grad_mr",
    drzava_mr.naz_drzave    AS "drzava_mr",
    grad_ms.naz_grada       AS "grad_ms",
    drzava_ms.naz_drzave    AS "drzava_ms"
FROM
         studentska_kartica
    INNER JOIN stanje_na_kartici ON studentska_kartica.br_kar = stanje_na_kartici.stud_kartica_br_kar
    INNER JOIN obrok ON obrok.sifra_ob = stanje_na_kartici.ob_sifra_ob
    INNER JOIN grad    grad_mr ON grad_mr.id_grada = studentska_kartica.id_grada_mr
    INNER JOIN drzava  drzava_mr ON drzava_mr.id_drzave = grad_mr.drzava_id_drzave
    INNER JOIN grad    grad_ms ON grad_ms.id_grada = studentska_kartica.id_grada_ms
    INNER JOIN drzava  drzava_ms ON drzava_ms.id_drzave = grad_ms.drzava_id_drzave
    INNER JOIN smer ON smer.sifra_smera = studentska_kartica.smer_sifra_smera
    INNER JOIN fakultet ON fakultet.id_fak = smer.fak_id_fak
    INNER JOIN status_studenta ON status_studenta.id_st = studentska_kartica.status_stud_id_st 
;

CREATE OR REPLACE VIEW Prodaja_obroka ( ime_rad, prez_rad, dat_izd_rac, uk_cena, kol_sta, iznos, cena_ob, naz_st, naz_ob, id_kase, sifra_rad ) AS
SELECT
    radnik.ime_rad,
    radnik.prez_rad,
    racun.dat_izd_rac,
    racun.uk_cena,
    stavka.kol_sta,
    stavka.iznos,
    cenovnik.cena_ob,
    status_studenta.naz_st,
    obrok.naz_ob,
    kasa.id_kase,
    radnik_u_szuo.sifra_rad
FROM
         racun
    INNER JOIN kasa ON kasa.id_kase = racun.kasa_id_kase
    INNER JOIN radnik_u_szuo ON radnik_u_szuo.sifra_rad = racun.radnik_u_szuo_sifra_rad
    INNER JOIN radnik ON radnik.sifra_rad = radnik_u_szuo.sifra_rad
    INNER JOIN stavka ON racun.id_rac = stavka.rac_id_rac
    INNER JOIN cenovnik ON cenovnik.dat_pv = stavka.cen_dat_pv
    INNER JOIN status_studenta ON status_studenta.id_st = cenovnik.status_stud_id_st
    INNER JOIN obrok ON obrok.sifra_ob = cenovnik.ob_sifra_ob
    INNER JOIN radnik_u_szuo ON radnik.sifra_rad = radnik_u_szuo.sifra_rad 
;

CREATE OR REPLACE VIEW Radnici_u_menzi ( jmbg_rad, dat_rodj_rad, ime_rad, prez_rad, si_id_si, sifra_rad ) AS
SELECT
    radnik.jmbg_rad,
    radnik.dat_rodj_rad,
    radnik.ime_rad,
    radnik.prez_rad,
    radnik.si_id_si,
    radnik_u_menzi.sifra_rad
FROM
         radnik_u_menzi
    INNER JOIN radnik ON radnik.sifra_rad = radnik_u_menzi.sifra_rad 
;

CREATE OR REPLACE VIEW Radnici_u_SZUO ( si_id_si, prez_rad, ime_rad, dat_rodj_rad, jmbg_rad, sifra_rad ) AS
SELECT
    radnik.si_id_si,
    radnik.prez_rad,
    radnik.ime_rad,
    radnik.dat_rodj_rad,
    radnik.jmbg_rad,
    radnik_u_szuo.sifra_rad
FROM
         radnik
    INNER JOIN radnik_u_szuo ON radnik.sifra_rad = radnik_u_szuo.sifra_rad 
;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            20
-- CREATE INDEX                             0
-- ALTER TABLE                             46
-- CREATE VIEW                              7
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
